// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://kalackacceweswatowjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthbGFja2FjY2V3ZXN3YXRvd2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDg1NzAsImV4cCI6MjA2MDgyNDU3MH0.0vebL9vAe7Y_-vpGbddZchA4lwkjL9r8fPNJqzz-Ugs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);